### ISSUE TITLE
Off-hand support to disable tridents not working

### ISSUE THREAD

**Issue by DarkChromaMC** [sachingorkar102/Cosmin#14]
My config looks like this:
```
blacklist-materials:
  HEAD: []
  CHEST: []
  LEGS: []
  FEET: []
  OFFHAND:
  - 'TRIDENT'
```
